package com.db.dsg.model;

public enum SDGGoal {
    NO_POVERTY,
    ZERO_HUNGER,
    GOOD_HEALTH,
    QUALITY_EDUCATION,
    GENDER_EQUALITY,
    CLEAN_WATER,
    AFFORDABLE_ENERGY,
    DECENT_WORK,
    INDUSTRY_INNOVATION,
    REDUCED_INEQUALITIES,
    CLIMATE_ACTION,
    PEACE_JUSTICE,
    PARTNERSHIPS
}
