name: Example - Using gcloud
on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # actions/checkout MUST come before auth
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          export_environment_variables: true
          project_id : hack-team-assertserviceunit
          workload_identity_provider: projects/785558430619/locations/global/workloadIdentityPools/github-2023/providers/github-2023
          service_account: infrastructure@hack-team-assertserviceunit.iam.gserviceaccount.com

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Create storage bucket'
        run: 'gcloud storage buckets create "gs://hack-team-assertserviceunit_github_bucket" --location=europe-west1 --uniform-bucket-level-access --public-access-prevention'
