name: Build & Push Spring Boot App to Artifact Registry

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          export_environment_variables: true
          project_id: hack-team-assertserviceunit
          workload_identity_provider: projects/785558430619/locations/global/workloadIdentityPools/github-2023/providers/github-2023
          service_account: workload@hack-team-assertserviceunit.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Java & Maven
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Spring Boot app
        working-directory: digital-saving-group
        run: mvn clean package -DskipTests


      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Generate Dockerfile
        working-directory: digital-saving-group
        run: |
          cat <<EOF > Dockerfile
          FROM eclipse-temurin:17-jdk
          ARG JAR_FILE=target/*.jar
          COPY \${JAR_FILE} app.jar
          ENTRYPOINT ["java", "-jar", "app.jar"]
          EOF

      - name: Build Docker image
        working-directory: digital-saving-group
        run: docker build -t us-central1-docker.pkg.dev/hack-team-assertserviceunit/backend-image/backend:latest .

      - name: Push Docker image to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/hack-team-assertserviceunit/backend-image/backend:latest
